openapi: 3.0.1
info:
  title: Ecommerce API
  description: API for managing an e-commerce platform
servers:
  - url: http://localhost:8080
paths:
  /carts:
    get:
      summary: Retrieves all carts from the database
      tags:
        - Carts
      responses:
        "200":
          description: Successfully retrieved all carts
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Cart"
        "500":
          description: Internal server error
    post:
      summary: Creates a new cart
      tags: 
        - Carts
      requestBody:
        required: true
        content: 
          application/json:
            schema: 
              $ref: "#/components/requestBodies/CreateCart"
      responses:
        "200":
          description: Cart created successfully

  /carts/{cid}:
    get:
      summary: Retrieves a cart by its ID
      tags: 
        - Carts
      parameters: 
        - name: cid
          in: path
          required: true
          description: ID of the cart to retrieve
          schema:
            type: string
      responses:
        "200":
          description: Cart found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Cart"
        "500":
          description: Internal server error
    put:
      summary: Updates a cart by its ID
      tags: 
        - Carts
      parameters: 
        - name: cid
          in: path
          required: true
          description: ID of the cart to update
          schema:
            type: string
      requestBody:
        required: true
        content: 
          application/json:
            schema:
              $ref: "#/components/requestBodies/UpdateCart"
      responses:
        "200":
          description: Cart updated successfully
        "404":
          description: Cart not found
        "500":
          description: Internal server error
    delete:
      summary: Deletes a cart by its ID
      tags: 
        - Carts
      parameters: 
        - name: cid
          in: path
          required: true
          description: ID of the cart to delete
          schema:
            type: string
      responses:
        "200":
          description: Cart deleted successfully
        "404":
          description: Cart not found
        "500":
          description: Internal server error

components:
  schemas:
    Cart:
      type: object
      properties: 
        _id: 
          type: string
          description: ID generated by MongoDB
        products: 
          type: object
          description: Products in cart
      example: 
        _id: ObjectId'664ce86d28a2c7631430bf58'
        products: {
          {product: ObjectId('65f3e1edc2093e832f571ca3'),
          quantity: 1,}
        }
  requestBodies: 
    CreateCart:
      type: object
      properties: 
       products: 
          type: object
          description: Products in cart
    UpdateCart:
      type: object
      properties: 
       products: 
          type: object
          description: Products in cart
      example: 
        _id: ObjectId'664ce86d28a2c7631430bf58'
        products: {
          {product: ObjectId('65f3e1edc2093e832f571ca3'),
          quantity: 1,}
        }